kind: deploymentPlan
namespace: staging
database:
  liquibaseChangeLogs:
    - v1.0.0
    - v1.1.0
    - v1.2.0
  url: jdbc:postgresql://wordsmith-staging.ca3tifbqfpuf.us-east-1.rds.amazonaws.com:5432/wordsmith
  credentials: 
      jenkinsCredentialsId: postgresql-admin.staging
applications:
  - release: wordsmith-api-staging
    chart: wordsmith/wordsmith-api
    version: 1.0.22
    values: wordsmith-api/values.yaml
    credentials:
      - jenkinsCredentialsId: postgresql.staging
        helmUsernameParameter: database.username
        helmPasswordParameter: database.password
  - release: wordsmith-front-staging
    chart: wordsmith/wordsmith-front
    version: "20180912.1205"
    values: wordsmith-front/values.yaml
  - release: wordsmith-another-api-staging
    chart: wordsmith/wordsmith-another-api
    version: 20180912-0831
    values: wordsmith-another-api/values.yaml
