kind: deploymentPlan
namespace: staging
database:
  liquibaseLevel: 1.2.3
  credentials:
    PG_SQL_CREDS: 
      jenkinsCredentialsId: postgresql.staging
applications:
  - release: wordsmith-api-staging
    chart: wordsmith/wordsmith-api
    version: 1.0.10
    probe: https://api.staging.wordsmith.beescloud.com/actuator/health
    values: wordsmith-api/values.yaml
    credentials:
      - jenkinsCredentialsId: postgresql.staging
        helmUsernameParameter: database.username
        helmPasswordParameter: database.password
  - release: wordsmith-front-staging
    chart: wordsmith/wordsmith-front
    version: 20180910-2020
    probe: https://front.staging.wordsmith.beescloud.com/
    values: wordsmith-front/values.yaml


