kind: deploymentPlan
namespace: staging
database:
  liquibaseChangeLogs:
    - v1.0.0
    - v1.1.0
  url: jdbc:postgresql://wordsmith-staging.ca3tifbqfpuf.us-east-1.rds.amazonaws.com:5432/wordsmith
  credentials: 
      jenkinsCredentialsId: postgresql-admin.staging
applications:
  - release: wordsmith-api-staging
    chart: wordsmith/wordsmith-api
    version: 1.0.11
    probe: https://api.staging.wordsmith.beescloud.com/actuator/health
    values: wordsmith-api/values.yaml
    credentials:
      - jenkinsCredentialsId: postgresql.staging
        helmUsernameParameter: database.username
        helmPasswordParameter: database.password
  - release: wordsmith-front-staging
    chart: wordsmith/wordsmith-front
    version: 20180910-2020
    probe: https://front.staging.wordsmith.beescloud.com/
    values: wordsmith-front/values.yaml


