kind: deploymentPlan
database:
  liquibaseLevel: 1.2.3
  credentials:
    PG_SQL_CREDS: 
      jenkinsCredentialsId: postgresql.staging
applications:
  - release: wordsmith-api-production
    chart: wordsmith/wordsmith-api
    version: 1.0.8
    probe: https://api.staging.wordsmith.beescloud.com/actuator/health    
    credentials:
      - jenkinsCredentialsId: postgresql.staging
        helmUsernameParameter: database.username 
        helmPasswordParameter: database.password 
  - release: wordsmith-front-production
    chart: wordsmith/wordsmith-front
    version: 20180910-1259


